name: mt_iabg_hadoop_cluster
services:
  # Parte 1: Instalación del clúster Hadoop
  # Parte 2: Ejecución de un trabajo MapReduce
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
      - "9010:9010"
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_namenode_data:/hadoop/dfs/name
      - ./jmx_prometheus_javaagent.jar:/opt/jmx_exporter/jmx_prometheus_javaagent.jar
      - ./jmx_config.yml:/opt/jmx_exporter/jmx_config.yml

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    hostname: resourcemanager
    restart: always
    ports:
      - "8088:8088"
    env_file:
      - ./hadoop.env
    volumes:
      - ./jmx_prometheus_javaagent.jar:/opt/jmx_exporter/jmx_prometheus_javaagent.jar
      - ./jmx_config.yml:/opt/jmx_exporter/jmx_config.yml

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    hostname: datanode1
    restart: always
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    ports:
      - "9864:9864"
      - "9011:9010"
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
      - ./jmx_prometheus_javaagent.jar:/opt/jmx_exporter/jmx_prometheus_javaagent.jar
      - ./jmx_config.yml:/opt/jmx_exporter/jmx_config.yml

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    hostname: datanode2
    restart: always
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    ports:
      - "9865:9864"
      - "9012:9010"
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
      - ./jmx_prometheus_javaagent.jar:/opt/jmx_exporter/jmx_prometheus_javaagent.jar
      - ./jmx_config.yml:/opt/jmx_exporter/jmx_config.yml

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    hostname: nodemanager
    restart: always
    depends_on:
      - resourcemanager
    env_file:
      - ./hadoop.env
    volumes:
      - ./jmx_prometheus_javaagent.jar:/opt/jmx_exporter/jmx_prometheus_javaagent.jar
      - ./jmx_config.yml:/opt/jmx_exporter/jmx_config.yml

  # Parte 3: Integración con Hive
  db-psql-metastore:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: db-psql-metastore
    restart: always
    depends_on:
      - namenode
    environment:
      - POSTGRES_PASSWORD=mine
      - POSTGRES_USER=hive
      - POSTGRES_DB=metastore_db
    # Añadimos salud del contenedor para que Hive espere a que la DB esté lista
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d metastore_db"]
      interval: 5s
      timeout: 5s
      retries: 5      
    ports:
      - "5432:5432"

  # Parte 4: Integración con Sqoop
  db-mysql-metastore:
    image: mysql:5.7
    container_name: db-mysql-metastore
    restart: always
    depends_on:
      - namenode
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sqoop_db
      - MYSQL_USER=user_sqoop
      - MYSQL_PASSWORD=pass_sqoop
    ports:
      # Como tengo WAMP instalado, lo abro en el 3307
      - "3307:3306" 
    # volumes:
    #   - ./mysql-connector-j-9.7.0.jar:/usr/local/sqoop/lib/mysql-connector-j-9.7.0.jar

  sqoop:
    image: dvoros/sqoop:latest
    container_name: sqoop
    restart: always
    depends_on:
      - namenode
      - db-mysql-metastore
      - hive-server
    env_file:
      - ./hadoop.env
    # Esto evita que el contenedor se detenga al fallar el script interno
    # command: ["tail", "-f", "/dev/null"]
    tty: true
    stdin_open: true
    volumes:
      - ./mysql-connector-j-9.7.0.jar:/jdbc/mysql-connector-j-9.7.0.jar
      # - ./mysql-connector-j-9.7.0.jar:/usr/local/sqoop/lib/mysql-connector-j-9.7.0.jar

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    depends_on:
      namenode:
        condition: service_started
      db-psql-metastore:
        condition: service_healthy      
    env_file:
      - ./hadoop.env
    environment:
      - "HIVE_SITE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://db-psql-metastore:5432/metastore_db"
      - "HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName=org.postgresql.Driver"
      - "HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName=hive"
      - "HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword=mine"
    ports:
      - "10000:10000"
    volumes:
      - hive_metastore:/opt/hive/metastore_db
      - ./jmx_prometheus_javaagent.jar:/opt/jmx_exporter/jmx_prometheus_javaagent.jar
      - ./jmx_config.yml:/opt/jmx_exporter/jmx_config.yml
    # Como hay RAM de sobra, indico un límite de memoria
    deploy:
      resources:
        limits:
          memory: 8G
  
  # Prometheus y Grafana para la monitorización
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
      - ./prom.alert.rules/alert.down_container.yml:/etc/prometheus/alert.down_container.yml
      - ./prom.alert.rules/alert.yarn_bottleneck.yml:/etc/prometheus/alert.yarn_bottleneck.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"

volumes:
  hadoop_namenode_data:
  hadoop_datanode1:
  hadoop_datanode2:
  hive_metastore:
